steps:
name: "Comandos Windows"
steps:
  - command: "hostname"
    label: "Nombre de mi computador"
  - command: "ipconfig"
    label: "Direcciones de red"
  # esperemos a que acabe de ejecutar ipconfig
  - wait
  # si falla cualquier paso anterior, igual sigue
    allow_dependency_failure: true
  - command: "python ./hello.py"
    label: "Executando hello.py"
  # Una intervencion manual
  - block: "¿Executamos bye.py?"
  # pidiendo variables para confirmar
    fields:
      - text: "Version"
        key: "release-version"
      - select: "Rama"
        key: "release-rama"
        default: "dev"
        options:
          - label: "Desarrollo"
            value: "dev"
          - label: "Estable"
            value: "Stable"
  - command: "python ./bye.py"
    label: "Executando bye.py"
    #si bye.py no se ejecuta, intenta 3 veces automaticamente
    retry:
      automatic:
        limit: 3
      # solo se si es master
    branches: "master"
    # ¿te demoraras como maximo 10 minutos?, si no, se cancela
    timeout_in_minutes: 10
